//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puantaj2017.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izin
    {
        public int id { get; set; }
        public int personelid { get; set; }
        public int yil { get; set; }
        public System.DateTime baslangictarih { get; set; }
        public System.DateTime bitistarihi { get; set; }
        public int izintip { get; set; }
        public string aciklama { get; set; }
        public int gun { get; set; }
    
        public virtual IzinTip IzinTip1 { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
