//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puantaj2017.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelMesai
    {
        public int id { get; set; }
        public int personelID { get; set; }
        public int yil { get; set; }
        public int ay { get; set; }
        public int mesai1 { get; set; }
        public int mesai2 { get; set; }
    
        public virtual Personel Personel { get; set; }
    }
}
