//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puantaj2017.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personel()
        {
            this.Avanslars = new HashSet<Avanslar>();
            this.birims = new HashSet<birim>();
            this.Izins = new HashSet<Izin>();
            this.PersonelGrups = new HashSet<PersonelGrup>();
            this.PersonelMesais = new HashSet<PersonelMesai>();
        }
    
        public int id { get; set; }
        public string adsoyad { get; set; }
        public Nullable<int> birimid { get; set; }
        public bool puantaj { get; set; }
        public Nullable<int> sira { get; set; }
        public string sicilno { get; set; }
        public string tcno { get; set; }
        public Nullable<int> pdksid { get; set; }
        public Nullable<System.DateTime> giristarihi { get; set; }
        public Nullable<System.DateTime> kidemtarihi { get; set; }
        public Nullable<System.Guid> mikroid { get; set; }
        public Nullable<System.DateTime> dogumtarihi { get; set; }
        public Nullable<System.DateTime> cikistarihi { get; set; }
        public Nullable<int> kadro { get; set; }
        public string iban { get; set; }
        public Nullable<bool> yaka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avanslar> Avanslars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<birim> birims { get; set; }
        public virtual birim birim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izin> Izins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelGrup> PersonelGrups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelMesai> PersonelMesais { get; set; }
    }
}
