//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puantaj2017.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Takip
    {
        public int id { get; set; }
        public string aciklama { get; set; }
        public System.DateTime ekleme { get; set; }
        public Nullable<System.DateTime> tamamlanma { get; set; }
        public System.DateTime sontarih { get; set; }
    }
}
