//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puantaj2017.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vergi_dilim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vergi_dilim()
        {
            this.vergi_dilim_detay = new HashSet<vergi_dilim_detay>();
        }
    
        public int id { get; set; }
        public int yil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vergi_dilim_detay> vergi_dilim_detay { get; set; }
    }
}
