//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puantaj2017.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vergi_dilim_detay
    {
        public int id { get; set; }
        public int dilimId { get; set; }
        public int oran { get; set; }
        public decimal alt { get; set; }
        public decimal ust { get; set; }
    
        public virtual vergi_dilim vergi_dilim { get; set; }
    }
}
