using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.Spreadsheet;



namespace puantaj2017
{
  

    public partial class BES : Form
    {
        private delegate void AddListBoxItemDelegate(object item);
        private List<DBes> tcler;
        Workbook workbook = new Workbook();
        private string filename;
        public BES()
        {
            tcler = new List<DBes>();
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a ExcelDataSource

        }

        private void BES_Load(object sender, EventArgs e)
        {

        }

        private void besexcel_Click(object sender, EventArgs e)
        {
            OpenFileDialog open = new OpenFileDialog();
            open.InitialDirectory = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
            open.Filter = "Excel Dosyası (*.xls)|*.xls";
            open.FileOk += Open_FileOk;
            open.ShowDialog();
            filename = open.FileName;


            workbook = new Workbook();

            // Load a workbook from the stream. 

            workbook.LoadDocument(filename);

            var bottom = workbook.Worksheets[0].Cells.CurrentRegion.BottomRowIndex + 1;

            using (var db = new MikroDB_V15_KENTEntities())
            {
                for (int i = 2; i <= bottom; i++)
                {
                    var tc = workbook.Worksheets[0].Cells["A" + i].Value.ToString();
                    //tutar G de
                    tcler.Add(new DBes()
                    {
                        TC = tc
                    });

                    //var query = (from p in db.PERSONELLERs
                    //             join pt in db.PERSONEL_TAHAKKUKLARI
                    //                 on p.per_kod equals pt.pt_pkod
                    //             where p.per_sicil_no == tc & pt.pt_maliyil == yil & pt.pt_tah_ay == ay
                    //             select pt.pt_otobes_tutari);

                    ////mikrodan bes tutarını çek
                    //Console.WriteLine(tc + ' ' + query.FirstOrDefault());
                    //workbook.Worksheets[0].Cells["G" + i].Value = query.FirstOrDefault();

                }
            }
            // workbook.SaveDocument(filename);


            listBoxControl1.Items.Add(tcler.Count + " adet kayıt bulundu");}
        private void Open_FileOk(object sender, CancelEventArgs e)
        {

        }

        private void BesKaydet(string filename, int yil, int ay)
        {
            try
            {
                Workbook workbook = new Workbook();

                // Load a workbook from the stream. 

                workbook.LoadDocument(filename);
                //Worksheet worksheet = workbook.Worksheets["TAHSILAT"];
                //Console.WriteLine(worksheet.Cells["B1"].Value);

                //worksheet.Cells["B1"].Value = DateTime.Now;//worksheet.Cells["B2"].Value = Math.PI;
                //worksheet.Cells["B3"].Value = "Have a nice day!";
                var bottom = workbook.Worksheets[0].Cells.CurrentRegion.BottomRowIndex + 1;

                using (var db = new MikroDB_V15_KENTEntities())
                {
                    for (int i = 2; i <= bottom; i++)
                    {
                        var tc = workbook.Worksheets[0].Cells["A" + i].Value.ToString();
                        //tutar G de

                        var query = (from p in db.PERSONELLERs
                                     join pt in db.PERSONEL_TAHAKKUKLARI
                                         on p.per_kod equals pt.pt_pkod
                                     where p.per_sicil_no == tc & pt.pt_maliyil == yil & pt.pt_tah_ay == ay
                                     select pt.pt_otobes_tutari);

                        //mikrodan bes tutarını çek
                        Console.WriteLine(tc + ' ' + query.FirstOrDefault());
                        workbook.Worksheets[0].Cells["G" + i].Value = query.FirstOrDefault();

                    }
                }
                workbook.SaveDocument(filename);

            }
            catch (Exception x)
            {


            }
        }

        private void button1_Click(object sender, EventArgs e)
        {
            if (tcler.Count < 1)
            {
                MessageBox.Show("Kayıt bulunamadı");
                return;}

            using (var db = new MikroDB_V15_KENTEntities())
            {
                var yil = int.Parse(comboBox1.SelectedItem.ToString());
                var ay = comboBox2.SelectedIndex + 1;//tüm kayıtları gir
                foreach (var tc in tcler)
                {//tutar G de

                    var bes = tc;
                    var query = (from p in db.PERSONELLERs
                                 join pt in db.PERSONEL_TAHAKKUKLARI
                                     on p.per_kod equals pt.pt_pkod
                                 where p.per_sicil_no == tc.TC & pt.pt_maliyil == yil & pt.pt_tah_ay == ay
                                 select pt.pt_otobes_tutari);
                    var firstOrDefault = query.FirstOrDefault();
                    if (firstOrDefault != null) tc.Tutar = (int)(firstOrDefault.Value);

                    //listBoxControl1.Items.Add(string.Format("{0} - {1} ",tc,query.FirstOrDefault()));

                }
            }

            var bottom = workbook.Worksheets[0].Cells.CurrentRegion.BottomRowIndex + 1;


            for (int i = 2; i <= bottom; i++)
            {
                var tc = workbook.Worksheets[0].Cells["A" + i].Value.ToString();
                //mikrodan bes tutarını çek
                int tutar = tcler.FirstOrDefault(c => c.TC == tc).Tutar;
                workbook.Worksheets[0].Cells["G" + i].Value = tutar;
                workbook.Worksheets[0].Cells["E" + i].Value = string.Format("{0}/{1}", comboBox1.Text,comboBox2.SelectedIndex + 1);
                workbook.Worksheets[0].Cells["F" + i].Value = DateTime.Now.AddDays(1).ToShortDateString();
                listBoxControl1.Items.Add(tc + ' ' + tutar);}
            workbook.SaveDocument(filename);



        }
    }
    public class DBes
    {
        public string TC { get; set; }
        public int Tutar { get; set; }
    }

}
