//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puantaj2017
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MikroDB_V15_KENTEntities : DbContext
    {
        public MikroDB_V15_KENTEntities()
            : base("name=MikroDB_V16_KENTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PERSONEL_AILE_TANIMLARI> PERSONEL_AILE_TANIMLARI { get; set; }
        public virtual DbSet<PERSONEL_IZINLERI> PERSONEL_IZINLERI { get; set; }
        public virtual DbSet<PERSONEL_TAHAKKUKLARI> PERSONEL_TAHAKKUKLARI { get; set; }
        public virtual DbSet<PERSONELLER> PERSONELLERs { get; set; }
    }
}
