//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puantaj2017
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONEL_AILE_TANIMLARI
    {
        public System.Guid PA_Guid { get; set; }
        public short PA_DBCno { get; set; }
        public Nullable<int> PA_SpecRECno { get; set; }
        public Nullable<bool> PA_iptal { get; set; }
        public Nullable<short> PA_fileid { get; set; }
        public Nullable<bool> PA_hidden { get; set; }
        public Nullable<bool> PA_kilitli { get; set; }
        public Nullable<bool> PA_degisti { get; set; }
        public Nullable<int> PA_checksum { get; set; }
        public Nullable<short> PA_create_user { get; set; }
        public System.DateTime PA_create_date { get; set; }
        public Nullable<short> PA_lastup_user { get; set; }
        public Nullable<System.DateTime> PA_lastup_date { get; set; }
        public string PA_special1 { get; set; }
        public string PA_special2 { get; set; }
        public string PA_special3 { get; set; }
        public string PA_PerKodu { get; set; }
        public Nullable<byte> PA_Yakinlik { get; set; }
        public Nullable<short> PA_CocukSiraNo { get; set; }
        public string PA_Ad { get; set; }
        public string PA_Soyad { get; set; }
        public string PA_IlkSoyad { get; set; }
        public string PA_TcKimlik { get; set; }
        public Nullable<byte> PA_Cinsiyet { get; set; }
        public Nullable<System.DateTime> PA_DogumTar { get; set; }
        public string PA_DogumYer { get; set; }
        public Nullable<byte> PA_Ucretli { get; set; }
        public Nullable<byte> PA_Tahsili { get; set; }
        public Nullable<byte> PA_Sakatlik { get; set; }
        public string PA_Cadde { get; set; }
        public string PA_Mahalle { get; set; }
        public string PA_Sokak { get; set; }
        public string PA_Semt { get; set; }
        public string PA_Apt_No { get; set; }
        public string PA_Daire_No { get; set; }
        public string PA_Posta_Kodu { get; set; }
        public string PA_Ilce { get; set; }
        public string PA_Il { get; set; }
        public string PA_Ulke { get; set; }
        public string PA_Adres_kodu { get; set; }
        public string PA_TelUlkeKodu { get; set; }
        public string PA_TelBolgekodu { get; set; }
        public string PA_TelNo1 { get; set; }
        public Nullable<System.DateTime> PA_EvlilikTarihi { get; set; }
        public Nullable<byte> PA_agine_tabii { get; set; }
        public Nullable<bool> PA_OgrenimeDevamEdiyor { get; set; }
        public Nullable<byte> PA_maas_banka { get; set; }
        public string PA_banka_hesapno { get; set; }
    }
}
