//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puantaj2017
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONEL_IZINLERI
    {
        public System.Guid pz_Guid { get; set; }
        public short pz_DBCno { get; set; }
        public Nullable<int> pz_SpecRECno { get; set; }
        public Nullable<bool> pz_iptal { get; set; }
        public Nullable<short> pz_fileid { get; set; }
        public Nullable<bool> pz_hidden { get; set; }
        public Nullable<bool> pz_kilitli { get; set; }
        public Nullable<bool> pz_degisti { get; set; }
        public Nullable<int> pz_checksum { get; set; }
        public Nullable<short> pz_create_user { get; set; }
        public System.DateTime pz_create_date { get; set; }
        public Nullable<short> pz_lastup_user { get; set; }
        public Nullable<System.DateTime> pz_lastup_date { get; set; }
        public string pz_special1 { get; set; }
        public string pz_special2 { get; set; }
        public string pz_special3 { get; set; }
        public Nullable<short> pz_izin_yil { get; set; }
        public string pz_pers_kod { get; set; }
        public Nullable<int> pz_izin_no { get; set; }
        public Nullable<byte> pz_izin_tipi { get; set; }
        public Nullable<byte> pz_gun_sayisi { get; set; }
        public Nullable<byte> pz_yol_izni { get; set; }
        public Nullable<System.DateTime> pz_baslangictarih { get; set; }
        public Nullable<System.Guid> pz_bagli_talep_uid { get; set; }
        public string pz_izin_aciklama { get; set; }
        public Nullable<System.DateTime> pz_gerceklesen_donus_tarihi { get; set; }
        public Nullable<byte> pz_izin_detay_tipi { get; set; }
        public Nullable<System.DateTime> pz_bitistarihi { get; set; }
        public Nullable<System.DateTime> pz_isbasitarihi { get; set; }
        public Nullable<double> pz_saat { get; set; }
        public Nullable<System.DateTime> pz_BaslamaSaati { get; set; }
    }
}
